// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPHa24ijsMzUX1gNDEKKVj1geCTbAttI',
    appId: '1:325543453167:web:943f960e1bc17fffc4161a',
    messagingSenderId: '325543453167',
    projectId: 'project-teknomo',
    authDomain: 'project-teknomo.firebaseapp.com',
    storageBucket: 'project-teknomo.appspot.com',
    measurementId: 'G-6C3GZBFZP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_FkntAK8rWVQd66SZ56BQg7V0jC9t7FI',
    appId: '1:325543453167:android:7d937d9492628da1c4161a',
    messagingSenderId: '325543453167',
    projectId: 'project-teknomo',
    storageBucket: 'project-teknomo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABlogi0hUJOTJRKpXnBzKX4QA72lsE_lQ',
    appId: '1:325543453167:ios:62c7231bd0908e5fc4161a',
    messagingSenderId: '325543453167',
    projectId: 'project-teknomo',
    storageBucket: 'project-teknomo.appspot.com',
    iosClientId: '325543453167-88b6lh4inp0t8g8sekh7em55k2gib5v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTeknomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABlogi0hUJOTJRKpXnBzKX4QA72lsE_lQ',
    appId: '1:325543453167:ios:62c7231bd0908e5fc4161a',
    messagingSenderId: '325543453167',
    projectId: 'project-teknomo',
    storageBucket: 'project-teknomo.appspot.com',
    iosClientId: '325543453167-88b6lh4inp0t8g8sekh7em55k2gib5v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTeknomo',
  );
}
